### ISSUE TITLE
Game crashes after editing

### ISSUE THREAD

**Issue by Mayki07** [matyalatte/UE4-DDS-Tools#14]
Hi, I use your tool quite often and it works great, however I ran into a problem where the game crashes after editing the uasset file. I am attaching a test file before and after editing. If you could solve the problem, I would be grateful.
[Test file.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/11071632/Test.file.zip)

**Comment by enarkay** [comment]
I am no expert but since the dev doesn't seem available at the moment, my advice would be to maybe try injecting the image with the following two options checked
- No mimaps
- Skip non-texture assets

**Comment by matyalatte** [comment]
Thank you guys for the infomation.
I fixed 2 bugs at d9894b2 and 0778741, and they are related to mipmaps.

Can you try the fixed version? It may be fix the error.
[hotfix-for-v0.5.0.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/11163494/hotfix-for-v0.5.0.zip)
Unzip and overwrite the `src` folder.

**Comment by Mayki07** [comment]
I'm not home at the moment, but I'll try it out this weekend and let you know if it works.

**Comment by Mayki07** [comment]
So I have tested it, with the hotfix it is already working. Thank you for the fix.

**Comment by matyalatte** [comment]
Thanks for the testing!
I'll close this issue after releasing v0.5.1
