### ISSUE TITLE
Idea : Possible to support other platform?

### ISSUE THREAD

**Issue by zerlkung** [matyalatte/UE4-DDS-Tools#18]
Hi, your tool is magic but can you make support other platform before repack to .uexp Ex. PS4 and Nintendo switch sir?

PS4 = gnf format

Nintendo switch un-swizzling 
https://gbatemp.net/threads/noesis-mod-tiling-texture-for-ue4.535571/

Regard.

**Comment by matyalatte** [comment]
Sorry, I don't have the motivation to learn about gnf and swizzling.

What I can do is inject DDS into uassets.
So, I need Python (or C++) modules that can convert between DDS and the platform specific formats.

If someone can provide the modules, I'll merge them into my tool.
But I don't plan to make them by myself now.
