### ISSUE TITLE
Problem with texture export

### ISSUE THREAD

**Issue by Mayki07** [matyalatte/UE4-DDS-Tools#19]
Hi, I have a game which is created in UE 4.27, but I can't export one texture using your tool. The tool doesn't recognize which version of the UE engine it is at all. Can you please help me with this?

I am attaching a test file.

![Error](https://github.com/matyalatte/UE4-DDS-Tools/assets/35667524/494a2acd-8889-422c-be81-f7253fe64394)

[Test.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/11981867/Test.zip)

**Comment by matyalatte** [comment]
Hi, I think your asset is broken.
All usset files should start with the specific 4-byte tag for any UE version.
But your asset starts with `00 00 00 00`.
I remember that I got a similar issue with [FModel](https://github.com/4sval/FModel).
[UE Viewer](https://github.com/gildor2/UEViewer/tree/master) worked for me at that time.

**Comment by Mayki07** [comment]
The problem is that FModel shows me the file and exports it as uasset, but UEviewer exports it as uexp. Unfortunately the file is in ucas and not in pak.

![FModel](https://github.com/matyalatte/UE4-DDS-Tools/assets/35667524/39ec7ed7-87ce-4b4c-82ca-aeb3feec2962)
![UEviewer](https://github.com/matyalatte/UE4-DDS-Tools/assets/35667524/4905c9ae-e540-4082-8761-5438e7ebcf39)

**Comment by Mayki07** [comment]
I used UEviewer from your link and the resulting uasset file is identical to the previous one.
[Test_uasset.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/11992473/Test_uasset.zip)

**Comment by matyalatte** [comment]
Umodel can't displays the exported assets too. So, I think they will export the binaries as they are but it's not the official .uasset formats. (maybe it's a customized format for ucas?)
I'll support the ucas things someday, but it'll take time.
Cause the format is a little bit different from the standard ones.

**Comment by Mayki07** [comment]
Alright, thanks for the reply and I'll hope for UCAS format support later on as it won't be long now and most UE games will have it.
