### ISSUE TITLE
Idea: Batch Injections

### ISSUE THREAD

**Issue by Crafty-The-Fox** [matyalatte/UE4-DDS-Tools#20]
This would be a very good feature for my workflow and maybe some other peoples workflows. 

How it would work is you have one folder with all of the texture files, each one is named the exact same as the uasset files. you select another folder with the uasset files, and then click inject and output all of the injections into the output folder.

**Comment by matyalatte** [comment]
It's already supported.
You can drop folders on the text boxes (or the batch files).

[Folder Injection · matyalatte/UE4-DDS-tools Wiki](https://github.com/matyalatte/UE4-DDS-tools/wiki/Folder-Injection)
