### ISSUE TITLE
UCAS support

### ISSUE THREAD

**Issue by matyalatte** [matyalatte/UE4-DDS-Tools#23]
Related to https://github.com/matyalatte/UE4-DDS-Tools/issues/19 and https://github.com/matyalatte/UE4-DDS-Tools/issues/22.

Recent UE games store assets in `.ucas` files, not `.pak`
Extraction tools (e.g. FModel) can extract the assets as `.uasset` but they are missing some attributes that the standard uasset files have.
So, UE4 DDS Tools should be able to detect the ucas assets, and skip the missing attributes.

**Comment by Mayki07** [comment]
Hi, can I ask if there is any progress with the UCAS problem?

**Comment by matyalatte** [comment]
My first attempt for ucas/utoc support was done at 938231b8935d651f7039eaed31af3a215200bd9d.

Tested with [a template project](https://docs.unrealengine.com/4.27/en-US/Resources/Templates/FirstPerson/).
I replaced a normal map of a weapon with a black image, and repacked assets with [UEcastoc](https://github.com/gitMenv/UEcastoc).
Then, the game app showed a player's weapon with broken normals.

Vanilla
![vanilla](https://github.com/matyalatte/UE4-DDS-Tools/assets/69258547/ff554e45-8d84-44c8-b7fe-a6af32922d63)

With broken normals
![broken_normal](https://github.com/matyalatte/UE4-DDS-Tools/assets/69258547/0b4b8a44-4745-4df3-9922-4f93b170f470)

I also tested with resized textures and the `force uncompressed` option. They worked fine.

**Comment by Mayki07** [comment]
Will it be possible to test this version?

**Comment by matyalatte** [comment]
I'll release a preview version this weekend, but you can use [the dev branch](https://github.com/matyalatte/UE4-DDS-Tools/tree/dev) if you want to.
Here is the latest build.
[UE4-DDS-Tools-29f7af7-GUI.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/15130768/UE4-DDS-Tools-29f7af7-GUI.zip)

You can also folk my repo and run [the building workflow](https://github.com/matyalatte/UE4-DDS-Tools/actions/workflows/build.yml) to make `UE4-DDS-Tools-*.zip` by yourself.
Tutorial for my workflows is here.
https://github.com/matyalatte/tuw/blob/main/docs/Github-Actions.md

**Comment by Mayki07** [comment]
Hi, I have tried the DEV version of your tools, I have an asset with a texture exported from a UCAS file from UE 4.27 and it works fine there. Then I have an asset with texture from UE 5.2 and it fails to export. It always ends up with an error message see screen. 
The files for the test are attached.

![DDS](https://github.com/matyalatte/UE4-DDS-Tools/assets/35667524/b6266f2c-7077-4783-b234-f5788fefa29a)

![T_PoliceStation_Posters_01_a](https://github.com/matyalatte/UE4-DDS-Tools/assets/35667524/5f290d43-39f1-4413-8884-abbb0b5ccb3b)

Test file:
[Robocop_Posters.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/15133683/Robocop_Posters.zip)

**Comment by matyalatte** [comment]
Thanks for the testing.
Fixed the errors at 771b3533213df7206f8472994ada59ff3c0be3a0, and tested with UE4.27, 5.0, 5.2, 5.3 and 5.4.
I'll test it with 5.1 later. (I'm downloading UE5.1 now.)

Here is the latest build.
[UE4-DDS-Tools-ac7b730-GUI.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/15138251/UE4-DDS-Tools-ac7b730-GUI.zip)

It still fails to read your `T_PoliceStation_Posters_01_a` but the cause is another issue (#30.)

**Comment by matyalatte** [comment]
Tested with UE5.1. and a preview version was released as [v0.6.0](https://github.com/matyalatte/UE4-DDS-Tools/releases/tag/v0.6.0).
I don't close this issue becuase there might still be some problems.
I'll close it when releasing the next version.
