### ISSUE TITLE
Warning: Unsupported pixel format. (PF_ETC2_RGBA)

### ISSUE THREAD

**Issue by BeanGTA** [matyalatte/UE4-DDS-Tools#26]
This file format is for mobile: Android, IOS.

**Comment by matyalatte** [comment]
Hi, sorry for the late reply. I worked on other projects recently.

I added support for `PF_ETC1`, `PF_ETC2_RGB`, and `PF_ETC2_RGBA` at 0f5db0f135d99b501118d182e7e5a6cb18eefa46.
Can you try it with your assets?
Overwrite the `src` folder with this zip. (or apply the commit by yourself)
[v0.5.4-ETC-update.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/13777230/v0.5.4-ETC-update.zip)

Please send me your assets if it doesn't work.

**Comment by BeanGTA** [comment]
> Hi, sorry for the late reply. I worked on other projects recently.
> 
> I added support for `PF_ETC1`, `PF_ETC2_RGB`, and `PF_ETC2_RGBA` at [0f5db0f](https://github.com/matyalatte/UE4-DDS-Tools/commit/0f5db0f135d99b501118d182e7e5a6cb18eefa46). Can you try it with your assets? Overwrite the `src` folder with this zip. (or apply the commit by yourself) [v0.5.4-ETC-update.zip](https://github.com/matyalatte/UE4-DDS-Tools/files/13777230/v0.5.4-ETC-update.zip)
> 
> Please send me your assets if it doesn't work.

It was successful and it moved from the ETC format to the B8G8R8A8 format. Thank you so much. 😉

**Comment by matyalatte** [comment]
> It was successful and it moved from the ETC format to the B8G8R8A8 format. Thank you so much. 😉

Glad to hear that.
If you want to keep the ETC format, you can use [Compressonator](https://github.com/GPUOpen-Tools/compressonator) to cook DDS as ETC2_RGBA.
Other texture formats will use the B8G8R8A8 format because my DDS converter doesn't support ETC.
