### ISSUE TITLE
Erro extract image!

### ISSUE THREAD

**Issue by jonastraducoes** [matyalatte/UE4-DDS-Tools#3]
hello, thank you very much for making a tool that extracts an image from uexp! I was testing your tool UE4-DDS-Tools-v0.2.5 and it is not correctly extracting the image in this file!

https://cdn.discordapp.com/attachments/807736398240022600/966651194787364874/you_dead_en.uasset
https://cdn.discordapp.com/attachments/807736398240022600/966651194573488178/you_dead_en.uexp

**Comment by matyalatte** [comment]
Thanks for the testing.
I tried with GUI but got red (or orange?) "you dead."
So, I think you used a batch file without the parameter for the UE version. Or you selected the wrong version.

See here if you used the batch file.
https://github.com/matyalatte/UE4-DDS-Tools/wiki/Batch-files
I added the info about the version settings.
