### ISSUE TITLE
Add 5.4 compatibilty

### ISSUE THREAD

**Issue by KIZILANDO** [matyalatte/UE4-DDS-Tools#32]
Hey, I just wanted to know if you will add 5.4 compatibilty from ucas files pls. Thanks !

**Comment by matyalatte** [comment]
UE5.4 support is already done at 603f3ffcff8ad0f32dee22d91defdcb451e3cebe.
And I'm working on ucas/utoc things now.
7b7f563826547e1e76c31ff1ecb323bcc267587f should work for UE5 assets but I've never tested in game yet. (cause Idk how to repack them.)
At least, it can extract textures from fortnite assets.

**Comment by KIZILANDO** [comment]
It works !!!! Thank you so much
