### ISSUE TITLE
Specify Texture Error Even Tho I specified one

### ISSUE THREAD

**Issue by Zer0cipher** [matyalatte/UE4-DDS-Tools#36]
![image_2024-04-30_230644](https://github.com/matyalatte/UE4-DDS-Tools/assets/137117988/7eb9fecc-b95e-4434-8c8c-44342b011dff)

**Comment by matyalatte** [comment]
Thanks for the report.
I confirmed that it was an issue of `GUI.exe`. It removed empty strings from arguments. So, your texture path was passed as a .uasset file, and python was not able to get a texture path.
Will be fixed with https://github.com/matyalatte/tuw/pull/31.

**Comment by matyalatte** [comment]
Fixed at 8e7e1bbd478cbedbae6a59eb3fcefb380234e24d.

The latest build is available here.
https://github.com/matyalatte/UE4-DDS-Tools/actions/runs/8922932485

I'll close this issue with v0.6.1 release.

**Comment by matyalatte** [comment]
> ok ty but can you also do me a favour? can you uptade blender uasset import addon? to work with ue5.4?

Sorry, I want to contribute to other projects for now.
Might work on it in the future tho.

**Comment by Zer0cipher** [comment]
ok i understand thanks anyway
