### ISSUE TITLE
Check file version not working.

### ISSUE THREAD

**Issue by jonastraducoes** [matyalatte/UE4-DDS-Tools#5]
Thanks for making the tool, I went to test version 3.0 and
function of checking the file version is not working anymore!

**Comment by matyalatte** [comment]
Thanks for the testing.
Can you overwrite `main.py` with this? I think I fixed the bug.
https://github.com/matyalatte/UE4-DDS-Tools/releases/download/v0.3.0/hotfix-for-check-mode.zip

**Comment by jonastraducoes** [comment]
Thank you very much, everything works fine.
