### ISSUE TITLE
Game trek to yomi  image edit uexp.

### ISSUE THREAD

**Issue by jonastraducoes** [matyalatte/UE4-DDS-Tools#6]
hello, I went to test with your tool in the game Trek to yomi, but when I see the image files it only has .uexp, it doesn't have .usseat.
I do not know if it is possible or if you are interested in analyzing this type of file, thanks.

~Desktop.zip~

**Comment by matyalatte** [comment]
It can't be.
Your .uexp files refer to name tables, and the binary format looks like the standard .uexp files.
So, there should be .uasset files that have the name table.
I think you failed to unpack .pak.

**Comment by matyalatte** [comment]
Disabled your link because we shouldn't share the game resources here.
And I'll close the issue because you seemed to get .uasset files.
